using EntityWebApi.Core.Attributes;
using EntityWebApi.Dtos.Internal.Enums;

namespace EntityWebApi.Dtos.Internal.Dtos
{
    public class PropertySelection
    {
        public Type AttributeType { get; set; } = typeof(DtoPropertyAttribute);
        public EntityPropertyTypes DefaultIncludes { get; set; } = EntityPropertyTypes.None;
        public EntityPropertyTypes IgnoreAttribute { get; set; } = EntityPropertyTypes.None;
        public bool SkipAutoGeneratedPropertiesOnAdd { get; set; } = false;
        public bool SkipAutoGeneratedPropertiesOnUpdate { get; set; } = false;
    }
}
