using EntityWebApi.Core.Attributes;
using EntityWebApi.Dtos.Internal.Enums;

namespace EntityWebApi.Dtos.Internal.Dtos
{
    public class TypeConfiguration
    {
        public string Suffix { get; set; } = null!;
        public string? IncludeSuffix { get; set; } = null;
        public EntityPropertyTypes DefaultIncludes { get; set; } = EntityPropertyTypes.None;
        public EntityPropertyTypes IgnoreAttribute { get; set; } = EntityPropertyTypes.None;
        public bool SkipAutoGeneratedPropertiesOnAdd { get; set; } = false;
        public bool SkipAutoGeneratedPropertiesOnUpdate { get; set; } = false;
        public Type AttributeType { get; private set; } = typeof(DtoPropertyAttribute);
        public TypeConfiguration SetAttributeType<T>() where T : DtoPropertyAttribute
        {
            AttributeType = typeof(T);
            return this;
        }
    }
}
