using AutoMapper;
using EntityWebApi.Core;
using Microsoft.EntityFrameworkCore;
using NUnit.Framework;
using Shouldly;
using System.Collections.ObjectModel;
using Tests.Shared;
using Tests.Shared.Dtos;
using Tests.Shared.Entities;

namespace EntityWebApi.AutoMapper.Tests
{
    public class MapperConfigurationExpressionExtensionsTests
    {
        private readonly DbContextOptions<DataContext> _dbContextOptions;
        public MapperConfigurationExpressionExtensionsTests()
        {
            _dbContextOptions = new DbContextOptionsBuilder<DataContext>()
               .UseInMemoryDatabase(Guid.NewGuid().ToString())
               .Options;
        }

        [Test]
        public void CreateEntityMaps_Map()
        {
            var dataContext = new DataContext(_dbContextOptions);
            var typeStore = new TypeStore();
            typeStore.Add(typeof(NoKeyItemDto));
            var item = new NoKeyItem { Value = 2 };

            var mapper = new MapperConfiguration(
                config => config.CreateEntityMaps(dataContext, typeStore, "Dto"))
                .CreateMapper();
            var mapped = mapper.MapNotNull<NoKeyItemDto>(item);
            var mappedBack = mapper.MapNotNull<NoKeyItem>(mapped);

            mapped.Value.ShouldBe(2);
            mappedBack.Value.ShouldBe(2);
        }

        [Test]
        public void CreateEntityMaps_TwoMaps()
        {
            var dataContext = new DataContext(_dbContextOptions);
            var typeStore = new TypeStore();
            typeStore.Add(typeof(ItemDto));
            typeStore.Add(typeof(Item2Dto));
            var item = new Item { Id = 2, Value = 3 };
            var item2 = new Item2 { Id = 3, Value = 4 };

            var mapper = new MapperConfiguration(
                config => config.CreateEntityMaps(dataContext, typeStore, "Dto"))
                .CreateMapper();
            var mapped = mapper.MapNotNull<ItemDto>(item);
            var mapped2 = mapper.MapNotNull<Item2Dto>(item2);

            mapped.Id.ShouldBe(2);
            mapped.Value.ShouldBe(3);
            mapped2.Id.ShouldBe(3);
            mapped2.Value.ShouldBe(4);
        }

        [Test]
        public void CreateEntityMaps_SkipAutoGeneratedKeyProperty()
        {
            var dataContext = new DataContext(_dbContextOptions);
            var typeStore = new TypeStore();
            typeStore.Add(typeof(ItemDto));
            var item = new Item { Id = 2, Value = 3 };

            var mapper = new MapperConfiguration(
                config => config.CreateEntityMaps(dataContext, typeStore, "Dto"))
                .CreateMapper();
            var mapped = mapper.MapNotNull<ItemDto>(item);
            var mappedBack = mapper.MapNotNull<Item>(mapped);

            mapped.Id.ShouldBe(2);
            mapped.Value.ShouldBe(3);
            mappedBack.Id.ShouldBe(0);
            mappedBack.Value.ShouldBe(3);
        }

        [Test]
        public void CreateEntityMaps_MapNested()
        {
            var dataContext = new DataContext(_dbContextOptions);
            var typeStore = new TypeStore();
            typeStore.Add(typeof(ItemDto));
            typeStore.Add(typeof(ItemWithChildsDto));
            var item = new ItemWithChilds
            {
                Id = 2,
                Value = 3,
                Items = new[]
                {
                    new Item { Id = 10, Value = 11 }
                }
            };

            var mappedItem = new MapperConfiguration(
                config => config.CreateEntityMaps(dataContext, typeStore, "Dto"))
                .CreateMapper().MapNotNull<ItemWithChildsDto>(item);
            mappedItem.Id.ShouldBe(2);
            mappedItem.Value.ShouldBe(3);
            mappedItem.Items.Length.ShouldBe(1);
            mappedItem.Items.First().Id.ShouldBe(10);
            mappedItem.Items.First().Value.ShouldBe(11);
        }

        [Test]
        public void CreateEntityMaps_ChildsUpdated()
        {
            var dataContext = new DataContext(_dbContextOptions);
            var typeStore = new TypeStore();
            typeStore.Add(typeof(ItemDto));
            typeStore.Add(typeof(ItemWithChildsDto));
            var dto = new ItemWithChildsDto
            {
                Id = 2,
                Value = 3,
                Items = new[]
                {
                    new ItemDto { Id = 10, Value = 1 },
                    new ItemDto { Id = 11, Value = 12 }
                }
            };
            var item = new ItemWithChilds
            {
                Id = 2,
                Value = 3,
                Items = new Collection<Item>
                {
                    new Item { Id = 10, Value = 11 },
                    new Item { Id = 12, Value = 13 }
                }
            };

            var mapper = new MapperConfiguration(
                config =>
                {
                    config.AddEntityFrameworkCoreCollectionMappers(dataContext);
                    config.CreateEntityMaps(dataContext, typeStore, "Dto");
                }).CreateMapper();
            mapper.Map(dto, item);

            item.Id.ShouldBe(2);
            item.Value.ShouldBe(3);
            item.Items.Count.ShouldBe(2);
            item.Items.Any(i => i.Id == 10 && i.Value == 1).ShouldBeTrue();
            item.Items.Any(i => i.Id == 0 && i.Value == 12).ShouldBeTrue();
        }

        [Test]
        public async Task CreateEntityMaps_ChildsUpdatedInDataContext()
        {
            var dataContext = new DataContext(_dbContextOptions);
            var typeStore = new TypeStore();
            typeStore.Add(typeof(ItemDto));
            typeStore.Add(typeof(ItemWithChildsDto));
            var dto = new ItemWithChildsDto
            {
                Id = 2,
                Value = 3,
                Items = new[]
                {
                    new ItemDto { Id = 10, Value = 1 },
                    new ItemDto { Id = 11, Value = 12 }
                }
            };
            var item = new ItemWithChilds
            {
                Id = 2,
                Value = 3,
                Items = new Collection<Item>
                {
                    new Item { Id = 10, Value = 11 },
                    new Item { Id = 12, Value = 13 }
                }
            };
            await dataContext.AddAsync(item);
            await dataContext.SaveChangesAsync();

            var mapper = new MapperConfiguration(
                config =>
                {
                    config.AddEntityFrameworkCoreCollectionMappers(dataContext);
                    config.CreateEntityMaps(dataContext, typeStore, "Dto");
                }).CreateMapper();
            mapper.Map(dto, item);
            await dataContext.SaveChangesAsync();

            var savedItem = dataContext.ItemsWithChilds
                .AsNoTracking()
                .Include(c => c.Items)
                .Single(item => item.Id == 2);
            savedItem.Id.ShouldBe(2);
            savedItem.Value.ShouldBe(3);
            savedItem.Items.Count.ShouldBe(2);
            savedItem.Items.Any(i => i.Id == 10 && i.Value == 1).ShouldBeTrue();
            savedItem.Items.Any(i => i.Id != 12 && i.Value == 12).ShouldBeTrue();
        }

        [Test]
        public void CreateMapToEntity_SkipAutoGeneratedKeyProperty()
        {
            var dataContext = new DataContext(_dbContextOptions);
            var entityType = dataContext.Model.GetEntityTypes().Single(e => e.ClrType == typeof(Item));
            var dto = new ItemDto { Id = 2, Value = 3 };

            var mapped = new MapperConfiguration(
                config => config.CreateMapToEntity(typeof(ItemDto), entityType))
            .CreateMapper().MapNotNull<Item>(dto);

            mapped.Id.ShouldBe(0);
            mapped.Value.ShouldBe(3);
        }

        [Test]
        public void CreateMapToEntity_SkipAutoGeneratedKeyPropertyMappingToExistingItem()
        {
            var dataContext = new DataContext(_dbContextOptions);
            var entityType = dataContext.Model.GetEntityTypes().Single(e => e.ClrType == typeof(Item));
            var dto = new ItemDto { Id = 2, Value = 4 };
            var item = new Item() { Id = 2, Value = 3 };

            new MapperConfiguration(
                config => config.CreateMapToEntity(typeof(ItemDto), entityType))
                .CreateMapper().Map(dto, item);

            item.Id.ShouldBe(2);
            item.Value.ShouldBe(4);
        }

        [Test]
        public void CreateMapToEntity_IgnorePropertyWithPrivateSetter()
        {
            var dataContext = new DataContext(_dbContextOptions);
            var entityType = dataContext.Model.GetEntityTypes().Single(e => e.ClrType == typeof(Item));
            var dto = new ItemPrivateSetterDto(2, 3);

            var mapped = new MapperConfiguration(
                config => config.CreateMapToEntity(typeof(ItemPrivateSetterDto), entityType))
                .CreateMapper().MapNotNull<Item>(dto);

            mapped.Id.ShouldBe(0);
            mapped.Value.ShouldBe(0);
        }

        [Test]
        public void CreateMapToEntity_IgnorePropertyWithPrivateSetterMappingToExistingItem()
        {
            var dataContext = new DataContext(_dbContextOptions);
            var entityType = dataContext.Model.GetEntityTypes().Single(e => e.ClrType == typeof(Item));
            var dto = new ItemPrivateSetterDto(2, 4);
            var item = new Item() { Id = 2, Value = 3 };

            new MapperConfiguration(
                config => config.CreateMapToEntity(typeof(ItemPrivateSetterDto), entityType))
                .CreateMapper().Map(dto, item);

            item.Id.ShouldBe(2);
            item.Value.ShouldBe(3);
        }

        [Test]
        public void CreateMapToEntity_IgnorePropertyWithProtectedSetter()
        {
            var dataContext = new DataContext(_dbContextOptions);
            var entityType = dataContext.Model.GetEntityTypes().Single(e => e.ClrType == typeof(Item));
            var dto = new ItemProtectedSetterDto(2, 3);

            var mapped = new MapperConfiguration(
                config => config.CreateMapToEntity(typeof(ItemProtectedSetterDto), entityType))
                .CreateMapper().MapNotNull<Item>(dto);

            mapped.Id.ShouldBe(0);
            mapped.Value.ShouldBe(0);
        }

        [Test]
        public void CreateMapToEntity_IgnorePropertyWithProtectedSetterMappingToExistingItem()
        {
            var dataContext = new DataContext(_dbContextOptions);
            var entityType = dataContext.Model.GetEntityTypes().Single(e => e.ClrType == typeof(Item));
            var dto = new ItemProtectedSetterDto(2, 4);
            var item = new Item() { Id = 2, Value = 3 };

            new MapperConfiguration(
                config => config.CreateMapToEntity(typeof(ItemProtectedSetterDto), entityType))
                .CreateMapper().Map(dto, item);

            item.Id.ShouldBe(2);
            item.Value.ShouldBe(3);
        }

        [Test]
        public void CreateMapToEntity_OptionalFieldPropertyWithValue()
        {
            var dataContext = new DataContext(_dbContextOptions);
            var entityType = dataContext.Model.GetEntityTypes().Single(e => e.ClrType == typeof(Item));
            var dto = new ItemOptionalPropertyDto(2, 4);
            var item = new Item() { Id = 2, Value = 3 };

            new MapperConfiguration(
                config => config.CreateMapToEntity(typeof(ItemOptionalPropertyDto), entityType))
                .CreateMapper().Map(dto, item);

            item.Id.ShouldBe(2);
            item.Value.ShouldBe(4);
        }

        [Test]
        public void CreateMapToEntity_IgnoreOptionalFieldPropertyWithoutValue()
        {
            var dataContext = new DataContext(_dbContextOptions);
            var entityType = dataContext.Model.GetEntityTypes().Single(e => e.ClrType == typeof(Item));
            var dto = new ItemOptionalPropertyDto(2);
            var item = new Item() { Id = 2, Value = 3 };

            new MapperConfiguration(
                config => config.CreateMapToEntity(typeof(ItemOptionalPropertyDto), entityType))
                .CreateMapper().Map(dto, item);

            item.Id.ShouldBe(2);
            item.Value.ShouldBe(3);
        }

        [Test]
        public void CreateMapsToEntity_Map()
        {
            var dataContext = new DataContext(_dbContextOptions);
            var typeStore = new TypeStore();
            typeStore.Add(typeof(NoKeyItemDto));
            var dto = new NoKeyItemDto { Value = 2 };

            var mapper = new MapperConfiguration(
                config => config.CreateMapsToEntity(dataContext, typeStore, "Dto"))
                .CreateMapper();
            var mapped = mapper.MapNotNull<NoKeyItem>(dto);

            mapped.Value.ShouldBe(2);
            Should.Throw<Exception>(() => mapper.MapNotNull<NoKeyItemDto>(mapped));
        }

        [Test]
        public void CreateMapsFromEntity_Map()
        {
            var dataContext = new DataContext(_dbContextOptions);
            var typeStore = new TypeStore();
            typeStore.Add(typeof(NoKeyItemDto));
            var item = new NoKeyItem { Value = 2 };

            var mapper = new MapperConfiguration(
                config => config.CreateMapsFromEntity(dataContext, typeStore, "Dto"))
                .CreateMapper();
            var mapped = mapper.MapNotNull<NoKeyItemDto>(item);

            mapped.Value.ShouldBe(2);
            Should.Throw<Exception>(() => mapper.MapNotNull<NoKeyItem>(mapped));
        }

        [Test]
        public void CreateMapFromEntity_MapToPropertyWithPrivateSetter()
        {
            var dataContext = new DataContext(_dbContextOptions);
            var entityType = dataContext.Model.GetEntityTypes().Single(e => e.ClrType == typeof(Item));
            var item = new Item() { Id = 2, Value = 3 };

            var mapped = new MapperConfiguration(
                config => config.CreateMap<Item, ItemPrivateSetterNoConstructorDto>())
                .CreateMapper().MapNotNull<ItemPrivateSetterNoConstructorDto>(item);

            mapped.Id.ShouldBe(2);
            mapped.Value.ShouldBe(3);
        }

        [Test]
        public void CreateMapToEntity_MapToPropertyWithPrivateSetterMappingToExistingItem()
        {
            var dataContext = new DataContext(_dbContextOptions);
            var entityType = dataContext.Model.GetEntityTypes().Single(e => e.ClrType == typeof(Item));
            var item = new Item() { Id = 2, Value = 3 };
            var dto = new ItemPrivateSetterNoConstructorDto();

            new MapperConfiguration(
                config => config.CreateMap<Item, ItemPrivateSetterNoConstructorDto>())
                .CreateMapper().Map(item, dto);

            dto.Id.ShouldBe(2);
            dto.Value.ShouldBe(3);
        }
    }
}