using EntityWebApi.Dtos.Internal.Dtos;

namespace EntityWebApi.Dtos.Internal.Mappers
{
    public static class TypeConfigurationExtensions
    {
        public static PropertySelection ToSelection(this TypeConfiguration configuration)
        {
            return new PropertySelection()
            {
                AttributeType = configuration.AttributeType,
                DefaultIncludes = configuration.DefaultIncludes,
                IgnoreAttribute = configuration.IgnoreAttribute,
                SkipAutoGeneratedPropertiesOnAdd = configuration.SkipAutoGeneratedPropertiesOnAdd,
                SkipAutoGeneratedPropertiesOnUpdate = configuration.SkipAutoGeneratedPropertiesOnUpdate
            };
        }
    }
}
