using EntityWebApi.Core.Attributes;
using EntityWebApi.Dtos.Internal.Dtos;
using EntityWebApi.Dtos.Internal.Enums;
using Microsoft.EntityFrameworkCore.Metadata;
using System.Reflection;

namespace EntityWebApi.Dtos.Internal.Extensions
{
    public static class EntityTypeExtensions
    {
        public static IEnumerable<PropertyInfo> GetDtoProperties(
            this IEntityType entityType,
            PropertySelection selection
        )
        {
            var primaryKeyNames = entityType.GetPrimaryKeyProperties()
                .Select(p => p.Name);
            var propertyTypeByName = primaryKeyNames
                    .Select(p => (Name: p, Flag: EntityPropertyTypes.PrimaryKey))
                .Concat(entityType.GetForeignKeyProperties()
                    .Where(p => !primaryKeyNames.Any(n => p.Name == n))
                    .Select(p => (p.Name, Flag: EntityPropertyTypes.ForeignKeys)))
                .Concat(entityType.GetNavigations()
                    .Select(p => (p.Name, Flag: EntityPropertyTypes.Navigations)))
                .Concat(entityType.GetSkipNavigations()
                    .Select(p => (p.Name, Flag: EntityPropertyTypes.SkipNavigations)))
                .ToDictionary(i => i.Name, i => i.Flag);
            var excludedProperties = new HashSet<string>();
            if (selection.SkipAutoGeneratedPropertiesOnAdd)
            {
                excludedProperties.UnionWith(entityType.GetProperties()
                    .Where(p => p.ValueGenerated.HasFlag(ValueGenerated.OnAdd)).Select(p => p.Name));
            }
            if (selection.SkipAutoGeneratedPropertiesOnUpdate)
            {
                excludedProperties.UnionWith(entityType.GetProperties()
                    .Where(p => p.ValueGenerated.HasFlag(ValueGenerated.OnUpdate)).Select(p => p.Name));
            }
            return entityType.ClrType.GetProperties().Where(p =>
            {
                if (excludedProperties.Contains(p.Name))
                {
                    return false;
                }
                if (!propertyTypeByName.TryGetValue(p.Name, out var propertyType))
                {
                    propertyType = EntityPropertyTypes.Regular;
                }
                var include = selection.DefaultIncludes.HasFlag(propertyType);
                if (selection.IgnoreAttribute.HasFlag(propertyType))
                {
                    return include;
                }
                var attribute = (DtoPropertyAttribute?)p.GetCustomAttributes(selection.AttributeType)
                    .FirstOrDefault(a => a.GetType() == selection.AttributeType);
                return attribute == null ? include : !attribute.Exclude;
            });
        }

        public static IEnumerable<IProperty> GetPrimaryKeyProperties(this IEntityType entityType)
        {
            return entityType.FindPrimaryKey()?.Properties ?? Array.Empty<IProperty>();
        }

        public static IEnumerable<INavigationBase> GetAllNavigations(this IEntityType entityType)
        {
            return entityType.GetNavigations()
                .AsEnumerable<INavigationBase>()
                .Concat(entityType.GetSkipNavigations());
        }
    }
}
