using EntityWebApi.Core;
using EntityWebApi.Core.Attributes;
using EntityWebApi.Core.Enums;
using EntityWebApi.Dtos.Internal.Dtos;
using EntityWebApi.Dtos.Internal.Enums;
using EntityWebApi.Dtos.Internal.Extensions;
using EntityWebApi.Dtos.Internal.Mappers;
using Microsoft.EntityFrameworkCore;
using System.Reflection;
using System.Reflection.Emit;

namespace EntityWebApi.Dtos
{
    public class DtoBuilder
    {
        private readonly IDictionary<string, TypeBuilder> _typeBuilders = new Dictionary<string, TypeBuilder>();
        private static readonly Lazy<ModuleBuilder> _lazyModuleBuilder = new(InitModuleBuilder);
        private static ModuleBuilder ModuleBuilder => _lazyModuleBuilder.Value;
        private static readonly EntityPropertyTypes allFieldsMask = EntityPropertyTypes.Regular | EntityPropertyTypes.ForeignKeys;

        public TypeStore Build()
        {
            var typeStore = new TypeStore();
            foreach (var typeBuilder in _typeBuilders.Values)
            {
                typeStore.Add(typeBuilder.CreateType());
            }
            return typeStore;
        }

        public DtoBuilder CreateDtos(DbContext dbContext, bool allFields = false, string suffix = "Dto", string? includeSuffix = null)
        {
            return CreateDtos<DtoPropertyAttribute>(dbContext, allFields, suffix, includeSuffix);
        }

        public DtoBuilder CreateKeyDtos(DbContext dbContext, string suffix = "KeyDto")
        {
            return CreateKeyDtos<DtoPropertyAttribute>(dbContext, suffix);
        }

        public DtoBuilder CreatePostDtos(DbContext dbContext, bool allFields = false,
            string suffix = "PostDto", string includeSuffix = "Dto")
        {
            return CreatePostDtos<DtoPropertyAttribute>(dbContext, allFields, suffix, includeSuffix);
        }

        public DtoBuilder CreatePutDtos(DbContext dbContext, bool allFields = false,
            string suffix = "PutDto", string includeSuffix = "Dto")
        {
            return CreatePutDtos<DtoPropertyAttribute>(dbContext, allFields, suffix, includeSuffix);
        }

        public DtoBuilder CreateDtos<TDtoPropertyAttribute>(DbContext dbContext, bool allFields = false, string suffix = "Dto", string? includeSuffix = null)
            where TDtoPropertyAttribute : DtoPropertyAttribute
        {
            return CreateDtos(dbContext, new TypeConfiguration()
            {
                Suffix = suffix,
                IncludeSuffix = includeSuffix,
                DefaultIncludes = allFields ? EntityPropertyTypes.PrimaryKey | allFieldsMask : EntityPropertyTypes.PrimaryKey,
                IgnoreAttribute = EntityPropertyTypes.PrimaryKey
            }.SetAttributeType<TDtoPropertyAttribute>());
        }

        public DtoBuilder CreateKeyDtos<TDtoPropertyAttribute>(DbContext dbContext, string suffix = "KeyDto")
            where TDtoPropertyAttribute : DtoPropertyAttribute
        {
            return CreateDtos(dbContext, new TypeConfiguration
            {
                Suffix = suffix,
                DefaultIncludes = EntityPropertyTypes.PrimaryKey,
                IgnoreAttribute = EntityPropertyTypes.All
            }.SetAttributeType<TDtoPropertyAttribute>());
        }

        public DtoBuilder CreatePostDtos<TDtoPropertyAttribute>(DbContext dbContext, bool allFields = false,
            string suffix = "PostDto", string includeSuffix = "Dto")
            where TDtoPropertyAttribute : DtoPropertyAttribute
        {
            return CreateDtos(dbContext, new TypeConfiguration()
            {
                Suffix = suffix,
                IncludeSuffix = includeSuffix,
                DefaultIncludes = allFields ? EntityPropertyTypes.PrimaryKey | allFieldsMask : EntityPropertyTypes.PrimaryKey,
                IgnoreAttribute = EntityPropertyTypes.None,
                SkipAutoGeneratedPropertiesOnAdd = true
            }.SetAttributeType<TDtoPropertyAttribute>());
        }

        public DtoBuilder CreatePutDtos<TDtoPropertyAttribute>(DbContext dbContext, bool allFields = false,
            string suffix = "PutDto", string includeSuffix = "Dto")
            where TDtoPropertyAttribute : DtoPropertyAttribute
        {
            return CreateDtos(dbContext, new TypeConfiguration()
            {
                Suffix = suffix,
                IncludeSuffix = includeSuffix,
                DefaultIncludes = allFields ? allFieldsMask : EntityPropertyTypes.None,
                IgnoreAttribute = EntityPropertyTypes.None,
                SkipAutoGeneratedPropertiesOnUpdate = true
            }.SetAttributeType<TDtoPropertyAttribute>());
        }

        public DtoBuilder CreateDtos(DbContext dbContext, TypeConfiguration configuration)
        {
            var entityTypes = dbContext.Model.GetEntityTypes();
            foreach (var entityType in entityTypes)
            {
                Add(ModuleBuilder.DefineType($"{entityType.Name}{configuration.Suffix}", TypeAttributes.Public | TypeAttributes.BeforeFieldInit));
            }
            foreach (var entityType in entityTypes)
            {
                var typeBuilder = Get($"{entityType.ClrType.Name}{configuration.Suffix}");
                var navigationsByName = entityType.GetAllNavigations().ToDictionary(n => n.Name, n => n);
                var dtoProperties = entityType.GetDtoProperties(configuration.ToSelection()).Select(p =>
                {
                    var type = p.PropertyType;
                    var dtoAttribute = (DtoPropertyAttribute?)p.GetCustomAttributes(configuration.AttributeType)
                        .SingleOrDefault(a => a.GetType() == configuration.AttributeType);
                    if (navigationsByName.TryGetValue(p.Name, out var navigation))
                    {
                        var includeSuffix = dtoAttribute?.IncludeSuffix ?? configuration.IncludeSuffix;
                        var targetEntityType = navigation.TargetEntityType;
                        var targetEntityName = targetEntityType.ClrType.Name;
                        var newTargetType = Get($"{targetEntityName}{includeSuffix ?? configuration.Suffix}") ??
                            throw new InvalidOperationException($"EntityWebApi: No type found for entity '{targetEntityName}' and suffixNavigations '{configuration.IncludeSuffix}'");
                        type = ReplaceEntityType(type, targetEntityType.ClrType, newTargetType);
                    }
                    var access = (p.GetGetMethod() == null ? PropertyAccess.None : PropertyAccess.Read) |
                                 (p.GetSetMethod() == null ? PropertyAccess.None : PropertyAccess.Write);
                    return new PropertyConfiguration(p.Name, type)
                        .WithAttributes(p.GetCustomAttributesData())
                        .MakeOptional(dtoAttribute?.Optional ?? false)
                        .SetAccess((dtoAttribute?.Access ?? PropertyAccess.ReadWrite) & access);

                });
                typeBuilder?.AddProperties(dtoProperties);
            }
            return this;
        }

        private static ModuleBuilder InitModuleBuilder()
        {
            var assemblyName = "EntityWebApi.Types.Dynamic";
            var assemblyBuilder = AssemblyBuilder.DefineDynamicAssembly(new AssemblyName(assemblyName), AssemblyBuilderAccess.Run);
            return assemblyBuilder.DefineDynamicModule(assemblyName);
        }

        private TypeBuilder? Get(string name)
        {
            _typeBuilders.TryGetValue(name, out var result);
            return result;
        }

        private void Add(TypeBuilder dto)
        {
            if (!_typeBuilders.TryAdd(dto.Name, dto))
            {
                throw new ArgumentException($"EntityWebApi: A dto with the name {dto.Name} is created multiple times");
            }
        }

        private static Type ReplaceEntityType(Type containingType, Type currentType, Type newType)
        {
            if (containingType.FullName == currentType.FullName)
            {
                return newType;
            }
            if (!containingType.IsGenericType)
            {
                ThrowInvalidReplacementException(containingType, newType);
            }
            var arguments = containingType.GetGenericArguments();
            if (arguments.Length != 1)
            {
                ThrowInvalidReplacementException(containingType, newType);
            }
            var newArgument = ReplaceEntityType(arguments[0], currentType, newType);
            return containingType.GetGenericTypeDefinition().MakeGenericType(newArgument);
        }

        private static void ThrowInvalidReplacementException(Type oldType, Type newType)
        {
            throw new InvalidOperationException($"EntityWebApi: Can not replace '{oldType.FullName}' with '{newType.FullName}'.");
        }
    }
}
